# Generated by Django 3.2.9 on 2021-11-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('team', models.CharField(max_length=10, null=True)),
                ('tag', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
