# Generated by Django 3.2.9 on 2021-11-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['team']},
        ),
        migrations.RemoveField(
            model_name='member',
            name='tag',
        ),
        migrations.AddField(
            model_name='member',
            name='introduce',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='school',
            field=models.CharField(max_length=100, null=True, verbose_name=['한국기술교육대학교', '순천향대학교']),
        ),
        migrations.AlterField(
            model_name='member',
            name='team',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='hashtag',
            field=models.ManyToManyField(null=True, to='introduce.HashTag'),
        ),
        migrations.AddField(
            model_name='member',
            name='interest',
            field=models.ManyToManyField(null=True, to='introduce.Interest'),
        ),
        migrations.AddField(
            model_name='member',
            name='participate',
            field=models.ManyToManyField(null=True, to='introduce.Participate'),
        ),
    ]
