# Generated by Django 3.2.9 on 2021-11-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduce', '0003_auto_20211115_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='hashtag',
            field=models.ManyToManyField(blank=True, to='introduce.HashTag'),
        ),
        migrations.AlterField(
            model_name='member',
            name='interest',
            field=models.ManyToManyField(blank=True, to='introduce.Interest'),
        ),
        migrations.AlterField(
            model_name='member',
            name='participate',
            field=models.ManyToManyField(blank=True, to='introduce.Participate'),
        ),
    ]
