# Generated by Django 3.2.9 on 2021-11-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='is_not_played',
            field=models.BooleanField(default=True),
        ),
    ]
